# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: acme/fraudcop/metrics/metric.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="acme/fraudcop/metrics/metric.proto",
    package="acme.fraudcop.metrics",
    syntax="proto2",
    serialized_options=None,
    serialized_pb=b'\n"acme/fraudcop/metrics/metric.proto\x12\x15\x61\x63me.fraudcop.metrics"\x99\x01\n\x06Metric\x12\x0e\n\x06metric\x18\x01 \x02(\t\x12\x14\n\x0cmetric_value\x18\x02 \x02(\x02\x12\x10\n\x08test_ids\x18\x03 \x03(\t\x12\x11\n\ttest_time\x18\x04 \x01(\x03\x12\x0c\n\x04mode\x18\x05 \x01(\t\x12\x0f\n\x07version\x18\x06 \x01(\t\x12\x12\n\nmodel_name\x18\x07 \x01(\t\x12\x11\n\tmodel_uri\x18\x08 \x01(\t',
)


_METRIC = _descriptor.Descriptor(
    name="Metric",
    full_name="acme.fraudcop.metrics.Metric",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="metric",
            full_name="acme.fraudcop.metrics.Metric.metric",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="metric_value",
            full_name="acme.fraudcop.metrics.Metric.metric_value",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=2,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="test_ids",
            full_name="acme.fraudcop.metrics.Metric.test_ids",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="test_time",
            full_name="acme.fraudcop.metrics.Metric.test_time",
            index=3,
            number=4,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="mode",
            full_name="acme.fraudcop.metrics.Metric.mode",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="version",
            full_name="acme.fraudcop.metrics.Metric.version",
            index=5,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="model_name",
            full_name="acme.fraudcop.metrics.Metric.model_name",
            index=6,
            number=7,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="model_uri",
            full_name="acme.fraudcop.metrics.Metric.model_uri",
            index=7,
            number=8,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=62,
    serialized_end=215,
)

DESCRIPTOR.message_types_by_name["Metric"] = _METRIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Metric = _reflection.GeneratedProtocolMessageType(
    "Metric",
    (_message.Message,),
    {
        "DESCRIPTOR": _METRIC,
        "__module__": "acme.fraudcop.metrics.metric_pb2"
        # @@protoc_insertion_point(class_scope:acme.fraudcop.metrics.Metric)
    },
)
_sym_db.RegisterMessage(Metric)


# @@protoc_insertion_point(module_scope)
